### ISSUE TITLE
异步IO操作有好的解决方法吗？

### ISSUE THREAD

**Issue by deepziyu** [tsingsun/yii2-daemon#1]
比如说同步PDO数据库操作转异步，异步缓存，异步日志。

**Comment by tsingsun** [comment]
这部分还没考虑怎么改写。。以后吧

**Comment by deepziyu** [comment]
这个才是性能的关键，这个我想来想去真的没有啥好办法，跟用go或者zanphp的成本相差无几。或许能有比较好的解决方式吧，加油。

**Comment by tsingsun** [comment]
用了swoole，对比php-fpm的性能提升已经是巨大了，很多小系统应该够用，对于异步IO的需求如果有那么迫切的话，就需要重写yii的db组件了。

**Comment by deepziyu** [comment]
对，我现在的想法是模仿 youzan/zan 重写db组件（仅仅支持msyql）， 缓存 用Swoole\Coroutine\Redis重写log组件，日志用logstash的Syslog模式。这样就可以全异步IO了。

**Comment by tsingsun** [comment]
现在的版本已经支持了
