### ISSUE TITLE
The file or directory to be published does not exist: /data/app/im/vendor/bower-asset/jquery/dist

### ISSUE THREAD

**Issue by WalkingSun** [tsingsun/yii2-daemon#5]
装了后报错了，
yii\base\InvalidArgumentException: The file or directory to be published does not exist: /data/app/im/vendor/bower-asset/jquery/dist in /data/app/im/vendor/yiisoft/yii2/web/AssetManager.php:456
Stack trace:
#0 /data/app/im/vendor/yiisoft/yii2/web/AssetBundle.php(185): yii\web\AssetManager->publish('/data/app/im/ve...', Array)
#1 /data/app/im/vendor/yiisoft/yii2/web/AssetManager.php(268): yii\web\AssetBundle->publish(Object(yii\web\AssetManager))
#2 /data/app/im/vendor/yiisoft/yii2/web/AssetManager.php(239): yii\web\AssetManager->loadBundle('yii\\web\\JqueryA...', Array, true)
#3 /data/app/im/vendor/yiisoft/yii2/web/View.php(286): yii\web\AssetManager->getBundle('yii\\web\\JqueryA...')
#4 /data/app/im/vendor/yiisoft/yii2/web/View.php(291): yii\web\View->registerAssetBundle('yii\\web\\JqueryA...', NULL)
#5 /data/app/im/vendor/yiisoft/yii2/web/View.php(291): yii\web\View->registerAssetBundle('yii\\web\\YiiAsse...', NULL)
#6 /data/app/im/vendor/yiisoft/yii2/web/AssetBundle.php(125): yii\web\View->registerAssetBundle('app\\assets\\AppA...')
#7 /data/app/im/views/layouts/main.php(13): yii\web\AssetBundle::register(Object(yii\web\View))
#8 /data/app/im/vendor/yiisoft/yii2/base/View.php(336): require('/data/app/im/vi...')
#9 /data/app/im/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/data/app/im/vi...', Array)
#10 /data/app/im/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/data/app/im/vi...', Array, Object(app\controllers\SiteController))
#11 /data/app/im/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#12 /data/app/im/controllers/SiteController.php(64): yii\base\Controller->render('index')
#13 [internal function]: app\controllers\SiteController->actionIndex()
#14 /data/app/im/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /data/app/im/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /data/app/im/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array)
#17 /data/app/im/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#18 /data/app/im/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#19 /data/app/im/web/index.php(12): yii\base\Application->run()
#20 {main}
Copy Stacktrace Search Stackoverflow Search Google Exception
Invalid Argument – yii\base\InvalidArgumentException
The file or directory to be published does not exist: /data/app/im/vendor/bower-asset/jquery/dist

楼主，看看呐

**Comment by tsingsun** [comment]
提示很明显了哦,指不到Jq. AssetManager无法发布,跟你本机配置有关,不是swoole问题.

**Comment by WalkingSun** [comment]
本机配置，装之前没什么问题啊，配置应该没问题吧，安装了这个组件后就报问题了，跟yii版本有没有关系啊，yii2-app-basic basic 2.0.14

**Comment by tsingsun** [comment]
/data/app/im/vendor/bower-asset/jquery/dist 存在相应的文件吗? 然后看看swoole的配置的用户与权限是否有问题.

**Comment by WalkingSun** [comment]
没有出现bower-asset这个目录，纳闷

**Comment by dickens7** [comment]
**compose.json中定义的的 `replace` 导致 包被移除了**
```json
{
    "replace": {
        "bower-asset/jquery": "*",
        "bower-asset/bootstrap": "*",
        "bower-asset/inputmask": "*",
        "bower-asset/punycode": "*",
        "bower-asset/typeahead.js": "*",
        "bower-asset/yii2-pjax": "*"
    }
}
```

**Comment by WalkingSun** [comment]
> **compose.json中定义的的 `replace` 导致 包被移除了**
> 
> ```json
> {
>     "replace": {
>         "bower-asset/jquery": "*",
>         "bower-asset/bootstrap": "*",
>         "bower-asset/inputmask": "*",
>         "bower-asset/punycode": "*",
>         "bower-asset/typeahead.js": "*",
>         "bower-asset/yii2-pjax": "*"
>     }
> }
> ```
感谢，我想你是对的，但我用了另一个
