### ISSUE TITLE
关于一行代码的问题

### ISSUE THREAD

**Issue by sdscbr** [tsingsun/yii2-daemon#8]
文件位置：yii2-swoole/src/bootstrap/WebApp.php
在第44行，handleRequest方法中：
```php
$this->state = Application::STATE_HANDLING_REQUEST;
```
$this是不是应该修改为$app，因为在WebApp这个类中，包括它的父类BaseBootstrap都没有这个属性的定义， 虽然整体运行没有报错，想问一下这样写用 $this 而不用 $app 的原因，是否应修改成下面的：
```php
$app->state = Application::STATE_HANDLING_REQUEST;
```

**Comment by tsingsun** [comment]
是的,这是个bug,我发布,修版本在[2.3.2](https://github.com/tsingsun/yii2-swoole/releases/tag/2.3.2)

**Comment by sdscbr** [comment]
> 是的,这是个bug,我发布,修版本在[2.3.2](https://github.com/tsingsun/yii2-swoole/releases/tag/2.3.2)

ok，谢谢~~
